import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, ChevronRight, MapPin, Search, Users } from "lucide-react";

import { OrganizerLayout } from "@/components/site/OrganizerLayout";

export const Route = createFileRoute("/organizadores/eventos")({ component: EventsPage });

const events = [
  { name: "Circuito das Araucarias", type: "Corrida de rua", city: "Londrina, PR", date: "18 mai 2026", people: "842", status: "Inscricoes abertas", tone: "lime" },
  { name: "Maratona de Inverno", type: "Maratona", city: "Curitiba, PR", date: "02 jun 2026", people: "1.240", status: "Em destaque", tone: "primary" },
  { name: "Desafio Costa Oeste", type: "Ciclismo", city: "Foz do Iguacu, PR", date: "15 jun 2026", people: "516", status: "Inscricoes abertas", tone: "lime" },
  { name: "Travessia Ilha do Mel", type: "Natacao", city: "Pontal do Parana, PR", date: "29 jun 2026", people: "280", status: "Planejamento", tone: "orange" },
  { name: "Festival de Volei de Areia", type: "Volei", city: "Maringa, PR", date: "12 jul 2026", people: "96", status: "Planejamento", tone: "orange" },
];

function EventsPage() {
  return <OrganizerLayout active="Eventos"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-lime">Gestao de eventos</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Eventos</h1><p className="mt-2 text-sm text-muted-foreground">Organize sua agenda, acompanhe inscricoes e ative novas oportunidades.</p></div></div><div className="grid gap-4 sm:grid-cols-3"><Summary label="Total de eventos" value="24" /><Summary label="Eventos ativos" value="12" /><Summary label="Inscricoes no mes" value="2.698" /></div><section className="rounded-2xl border border-border bg-gradient-card p-5 shadow-card sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Sua agenda</h2><p className="mt-1 text-sm text-muted-foreground">5 eventos encontrados</p></div><label className="flex min-w-52 flex-1 items-center gap-2 rounded-xl border border-input bg-background/60 px-3 py-2 text-sm text-muted-foreground sm:max-w-xs"><Search className="h-4 w-4" /><input className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-muted-foreground" placeholder="Buscar evento" /></label></div><div className="mt-5 space-y-3">{events.map((event) => <div key={event.name} className="flex flex-col gap-4 rounded-xl border border-border bg-background/30 p-4 transition-colors hover:border-primary/50 sm:flex-row sm:items-center"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${event.tone === "lime" ? "bg-lime/15 text-lime" : event.tone === "orange" ? "bg-orange/15 text-orange" : "bg-primary/15 text-primary"}`}><CalendarDays className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{event.name}</p><p className="mt-1 text-sm text-muted-foreground">{event.type} <span className="mx-1">·</span> {event.city}</p></div><div className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm sm:block sm:w-32"><p className="text-muted-foreground">Data</p><p className="font-medium">{event.date}</p></div><div className="grid grid-cols-2 gap-x-6 gap-y-1 text-sm sm:block sm:w-28"><p className="text-muted-foreground">Participantes</p><p className="inline-flex items-center gap-1 font-medium"><Users className="h-3.5 w-3.5 text-lime" />{event.people}</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${event.tone === "orange" ? "bg-orange/15 text-orange" : event.tone === "primary" ? "bg-primary/15 text-primary" : "bg-lime/15 text-lime"}`}>{event.status}</span><Link to="/organizadores/eventos" className="text-muted-foreground hover:text-foreground" aria-label={`Abrir ${event.name}`}><ChevronRight className="h-5 w-5" /></Link></div>)}</div></section></OrganizerLayout>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-border bg-gradient-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p></div>; }