import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Building2, Search, Star, Target } from "lucide-react";

import { OrganizerLayout } from "@/components/site/OrganizerLayout";

export const Route = createFileRoute("/organizadores/patrocinadores")({ component: SponsorsPage });

const sponsors = [
  { name: "Cooperativa Aurora", category: "Alimentacao e bebidas", city: "Cascavel, PR", investment: "R$ 180 mil", score: "96%", color: "bg-lime" },
  { name: "Muffato Supermercados", category: "Varejo", city: "Londrina, PR", investment: "R$ 120 mil", score: "91%", color: "bg-primary" },
  { name: "Unimed Parana", category: "Saude", city: "Curitiba, PR", investment: "R$ 95 mil", score: "88%", color: "bg-orange" },
  { name: "Sicredi Uniao", category: "Servicos financeiros", city: "Maringa, PR", investment: "R$ 75 mil", score: "84%", color: "bg-lime" },
  { name: "O Boticario", category: "Beleza e bem-estar", city: "Sao Jose dos Pinhais, PR", investment: "R$ 60 mil", score: "79%", color: "bg-primary" },
];

function SponsorsPage() {
  return <OrganizerLayout active="Patrocinadores"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-lime">Parcerias estrategicas</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Patrocinadores</h1><p className="mt-2 text-sm text-muted-foreground">Encontre marcas alinhadas ao publico e ao impacto dos seus eventos.</p></div></div><div className="grid gap-4 sm:grid-cols-3"><Summary icon={Building2} label="Marcas conectadas" value="38" /><Summary icon={Target} label="Oportunidades abertas" value="14" /><Summary icon={Star} label="Fit medio" value="87%" /></div><section className="rounded-2xl border border-border bg-gradient-card p-5 shadow-card sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Marcas recomendadas</h2><p className="mt-1 text-sm text-muted-foreground">Ordenadas por compatibilidade com seus eventos.</p></div><label className="flex min-w-52 flex-1 items-center gap-2 rounded-xl border border-input bg-background/60 px-3 py-2 text-sm text-muted-foreground sm:max-w-xs"><Search className="h-4 w-4" /><input className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-muted-foreground" placeholder="Buscar patrocinador" /></label></div><div className="mt-5 grid gap-3 md:grid-cols-2">{sponsors.map((sponsor) => <article key={sponsor.name} className="flex gap-4 rounded-xl border border-border bg-background/30 p-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${sponsor.color}/15`}><Building2 className="h-5 w-5 text-lime" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{sponsor.name}</h3><p className="mt-1 text-xs text-muted-foreground">{sponsor.category} <span className="mx-1">·</span> {sponsor.city}</p></div><span className="rounded-full bg-lime/15 px-2 py-1 text-xs font-bold text-lime">{sponsor.score} fit</span></div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-muted-foreground">Investimento estimado</span><span className="font-semibold">{sponsor.investment}</span></div><button className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Ver perfil <ArrowUpRight className="h-3.5 w-3.5" /></button></div></article>)}</div></section></OrganizerLayout>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof Building2; label: string; value: string }) { return <div className="rounded-2xl border border-border bg-gradient-card p-5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/15 text-primary"><Icon className="h-4 w-4" /></div><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 font-display text-3xl font-bold">{value}</p></div>; }