/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as OrganizadoresRouteImport } from './routes/organizadores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatrocinadoresRoiRouteImport } from './routes/patrocinadores_.roi'
import { Route as PatrocinadoresEventosRouteImport } from './routes/patrocinadores_.eventos'

const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresRoute = OrganizadoresRouteImport.update({
  id: '/organizadores',
  path: '/organizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoiRoute = PatrocinadoresRoiRouteImport.update({
  id: '/patrocinadores_/roi',
  path: '/patrocinadores/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresEventosRoute = PatrocinadoresEventosRouteImport.update({
  id: '/patrocinadores_/eventos',
  path: '/patrocinadores/eventos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinadores/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores/roi': typeof PatrocinadoresRoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinadores/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores/roi': typeof PatrocinadoresRoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/patrocinadores_/eventos': typeof PatrocinadoresEventosRoute
  '/patrocinadores_/roi': typeof PatrocinadoresRoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizadores'
    | '/patrocinadores'
    | '/patrocinadores/eventos'
    | '/patrocinadores/roi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizadores'
    | '/patrocinadores'
    | '/patrocinadores/eventos'
    | '/patrocinadores/roi'
  id:
    | '__root__'
    | '/'
    | '/organizadores'
    | '/patrocinadores'
    | '/patrocinadores_/eventos'
    | '/patrocinadores_/roi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizadoresRoute: typeof OrganizadoresRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PatrocinadoresEventosRoute: typeof PatrocinadoresEventosRoute
  PatrocinadoresRoiRoute: typeof PatrocinadoresRoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores': {
      id: '/organizadores'
      path: '/organizadores'
      fullPath: '/organizadores'
      preLoaderRoute: typeof OrganizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores_/roi': {
      id: '/patrocinadores_/roi'
      path: '/patrocinadores/roi'
      fullPath: '/patrocinadores/roi'
      preLoaderRoute: typeof PatrocinadoresRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores_/eventos': {
      id: '/patrocinadores_/eventos'
      path: '/patrocinadores/eventos'
      fullPath: '/patrocinadores/eventos'
      preLoaderRoute: typeof PatrocinadoresEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizadoresRoute: OrganizadoresRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PatrocinadoresEventosRoute: PatrocinadoresEventosRoute,
  PatrocinadoresRoiRoute: PatrocinadoresRoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
