/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as OrganizadoresRouteImport } from './routes/organizadores'
import { Route as IndexRouteImport } from './routes/index'

const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresRoute = OrganizadoresRouteImport.update({
  id: '/organizadores',
  path: '/organizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizadores': typeof OrganizadoresRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/organizadores' | '/patrocinadores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/organizadores' | '/patrocinadores'
  id: '__root__' | '/' | '/organizadores' | '/patrocinadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizadoresRoute: typeof OrganizadoresRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores': {
      id: '/organizadores'
      path: '/organizadores'
      fullPath: '/organizadores'
      preLoaderRoute: typeof OrganizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizadoresRoute: OrganizadoresRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
